# Generated by Django 3.2.7 on 2021-09-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20210903_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='changed',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
