# Generated by Django 3.2.7 on 2022-02-16 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='some',
            field=models.CharField(default=django.utils.timezone.now, max_length=4, verbose_name='Some test'),
            preserve_default=False,
        ),
    ]
