# Generated by Django 3.2.7 on 2022-02-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_rubric_some'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(limit_choices_to={'show': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
