# Generated by Django 3.2.7 on 2022-02-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_alter_advuser_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'price')},
        ),
    ]
