# Generated by Django 3.2.7 on 2022-04-01 15:17

import bboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_bb_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='some',
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[bboard.models.validate_even], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
