# Generated by Django 3.2.7 on 2022-09-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_message_privatemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='message',
        ),
    ]
