# Generated by Django 3.2.7 on 2022-09-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20220915_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('hide_notes', 'Можно скрыть заметки'),)},
        ),
    ]
