# Generated by Django 3.2.7 on 2022-10-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(to='testapp.Spare'),
        ),
    ]
